name: wf-develop-pr
on:
  pull_request:
    branches:
      - develop

jobs:
  develop-pr-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Lint HTML and CSS
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
      - name: Build Website #Dont have to install parcel as its a node js package and npx works fine without it
        run: npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./" ##1st file and itll travers recersiverly 

      

    